# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4_wU1cpi9-YJ-cQ3kYfqe6BYCdWSLRr

### **Calculadora** **Simples**
"""

# iniciando com os dois números

n1 = int(input("Digite o primeiro número de cálculo: "))
n2 = int(input("Digite o segundo número de cálculo: "))

# escolha de operação

operacao = input("Digite soma, subtração, multiplicação ou divisão: ")

# Realização da operação

if operacao == "soma":
    print(n1 + n2)

elif operacao == "subtração":
    print(n1 - n2)

elif operacao == "multiplicação":
    print(n1 * n2)

elif operacao == "divisão":
    print(n1 / n2)

else:
    print("Operação inválida")

"""# Nova seção"""